global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'sonarqube-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.0.6.10:4001']

      ####
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093
# rule_files:
#   - 'rules/*.yml'